version: "3"
services:
  frontend-backend1:
    image: spring-and-react:latest
    build: /home/kuba/Pulpit/CodersLab/spring-and-react/target/classes/public/auth
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/wrojees09?useUnicode=true&characterEncoding=utf8&useSSL=false
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/kuba/Pulpit/CodersLab/spring-and-react/target/classes/public/auth:/home/kuba/Pulpit/CodersLab/spring-and-react/target/classes/public/auth

  backend2:
    image: bananapp:latest
    ports:
      - "8082:8080"
    volumes:
      - /home/kuba/Pulpit/CodersLab/spring-and-react/target/classes/public/auth:/home/kuba/Pulpit/CodersLab/spring-and-react/target/classes/public/auth

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wrojees09
    volumes:
      - /home/kuba/Pulpit/bananas/db:/var/lib/mysql

  adminer:
   image: adminer
   ports:
      - "5000:8080"



