version: "3"
services:
  frontend-backend1:
    image: spring-and-react:latest
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/wrojees09?useUnicode=true&characterEncoding=utf8&useSSL=false
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root

  backend2:
    image: bananapp:latest
    ports:
      - "8082:8080"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/kuba/Desktop/bananas/settings/bananapp-264116-0483d7ffaad7.json

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wrojees09
    volumes:
      - db-data:/var/lib/mysql

  adminer:
   image: adminer
   ports:
      - "5000:8080"

volumes:
  db-data:


